'use client';

import { useState } from 'react';
import {
    Dialog,
    DialogContent,
    DialogHeader,
    DialogTitle,
    DialogFooter,
} from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Loader2, FileText, Eye } from 'lucide-react';
import {
    type InvoiceData,
    generateInvoiceData,
    generatePreviewInvoiceNumber,
    type GeneratedInvoice,
} from '@/lib/services/invoice-generator';
import { InvoicePreview } from './InvoicePreview';
import { createClient } from '@/lib/supabase/client';

interface CreateInvoiceDialogProps {
    open: boolean;
    onOpenChange: (open: boolean) => void;
    applicationId?: string;
    partnerId?: string;
    initialData?: Partial<InvoiceData>;
    onInvoiceCreated?: (invoiceId: string) => void;
}

export function CreateInvoiceDialog({
    open,
    onOpenChange,
    applicationId,
    partnerId,
    initialData,
    onInvoiceCreated,
}: CreateInvoiceDialogProps) {
    const [formData, setFormData] = useState<InvoiceData>({
        studentName: initialData?.studentName || '',
        courseName: initialData?.courseName || '',
        rtoName: initialData?.rtoName || '',
        tuitionFee: initialData?.tuitionFee || 0,
        materialFee: initialData?.materialFee || 0,
        applicationFee: initialData?.applicationFee || 0,
        otherFees: initialData?.otherFees || 0,
        discount: initialData?.discount || 0,
        notes: initialData?.notes || '',
        applicationId,
        partnerId,
    });

    const [isSaving, setIsSaving] = useState(false);
    const [showPreview, setShowPreview] = useState(false);
    const [previewInvoice, setPreviewInvoice] = useState<GeneratedInvoice | null>(null);

    const handleInputChange = (field: keyof InvoiceData, value: string | number) => {
        setFormData((prev) => ({ ...prev, [field]: value }));
    };

    const handlePreview = () => {
        const invoiceNumber = generatePreviewInvoiceNumber();
        const invoice = generateInvoiceData(invoiceNumber, formData);
        setPreviewInvoice(invoice);
        setShowPreview(true);
    };

    const handleSave = async () => {
        setIsSaving(true);
        try {
            const supabase = createClient();

            // Calculate total
            const total =
                formData.tuitionFee +
                formData.materialFee +
                formData.applicationFee +
                (formData.otherFees || 0) -
                (formData.discount || 0);

            // Insert invoice (invoice_number will be generated by DB trigger)
            const { data, error } = await supabase
                .from('invoices')
                .insert({
                    application_id: applicationId || null,
                    partner_id: partnerId || null,
                    student_name: formData.studentName,
                    course_name: formData.courseName,
                    rto_name: formData.rtoName,
                    tuition_fee: formData.tuitionFee,
                    material_fee: formData.materialFee,
                    application_fee: formData.applicationFee,
                    other_fees: formData.otherFees || 0,
                    discount: formData.discount || 0,
                    total_amount: total,
                    status: 'draft',
                    due_date: formData.dueDate || null,
                    notes: formData.notes || null,
                })
                .select('id')
                .single();

            if (error) throw error;

            if (data && onInvoiceCreated) {
                onInvoiceCreated(data.id);
            }

            onOpenChange(false);
        } catch (error) {
            console.error('Error creating invoice:', error);
        } finally {
            setIsSaving(false);
        }
    };

    return (
        <>
            <Dialog open={open} onOpenChange={onOpenChange}>
                <DialogContent className="max-w-lg">
                    <DialogHeader>
                        <DialogTitle className="flex items-center gap-2">
                            <FileText className="h-5 w-5" />
                            Create Invoice
                        </DialogTitle>
                    </DialogHeader>

                    <div className="space-y-4">
                        {/* Student Info */}
                        <div className="space-y-2">
                            <Label htmlFor="studentName">Student Name *</Label>
                            <Input
                                id="studentName"
                                value={formData.studentName}
                                onChange={(e) => handleInputChange('studentName', e.target.value)}
                                placeholder="Enter student name"
                            />
                        </div>

                        {/* Course Info */}
                        <div className="grid grid-cols-2 gap-4">
                            <div className="space-y-2">
                                <Label htmlFor="courseName">Course Name</Label>
                                <Input
                                    id="courseName"
                                    value={formData.courseName}
                                    onChange={(e) => handleInputChange('courseName', e.target.value)}
                                    placeholder="Course name"
                                />
                            </div>
                            <div className="space-y-2">
                                <Label htmlFor="rtoName">RTO Name</Label>
                                <Input
                                    id="rtoName"
                                    value={formData.rtoName}
                                    onChange={(e) => handleInputChange('rtoName', e.target.value)}
                                    placeholder="RTO name"
                                />
                            </div>
                        </div>

                        {/* Fees */}
                        <div className="grid grid-cols-2 gap-4">
                            <div className="space-y-2">
                                <Label htmlFor="tuitionFee">Tuition Fee</Label>
                                <Input
                                    id="tuitionFee"
                                    type="number"
                                    min="0"
                                    step="0.01"
                                    value={formData.tuitionFee}
                                    onChange={(e) =>
                                        handleInputChange('tuitionFee', parseFloat(e.target.value) || 0)
                                    }
                                />
                            </div>
                            <div className="space-y-2">
                                <Label htmlFor="materialFee">Material Fee</Label>
                                <Input
                                    id="materialFee"
                                    type="number"
                                    min="0"
                                    step="0.01"
                                    value={formData.materialFee}
                                    onChange={(e) =>
                                        handleInputChange('materialFee', parseFloat(e.target.value) || 0)
                                    }
                                />
                            </div>
                        </div>

                        <div className="grid grid-cols-2 gap-4">
                            <div className="space-y-2">
                                <Label htmlFor="applicationFee">Application Fee</Label>
                                <Input
                                    id="applicationFee"
                                    type="number"
                                    min="0"
                                    step="0.01"
                                    value={formData.applicationFee}
                                    onChange={(e) =>
                                        handleInputChange('applicationFee', parseFloat(e.target.value) || 0)
                                    }
                                />
                            </div>
                            <div className="space-y-2">
                                <Label htmlFor="otherFees">Other Fees</Label>
                                <Input
                                    id="otherFees"
                                    type="number"
                                    min="0"
                                    step="0.01"
                                    value={formData.otherFees || 0}
                                    onChange={(e) =>
                                        handleInputChange('otherFees', parseFloat(e.target.value) || 0)
                                    }
                                />
                            </div>
                        </div>

                        <div className="space-y-2">
                            <Label htmlFor="discount">Discount</Label>
                            <Input
                                id="discount"
                                type="number"
                                min="0"
                                step="0.01"
                                value={formData.discount || 0}
                                onChange={(e) =>
                                    handleInputChange('discount', parseFloat(e.target.value) || 0)
                                }
                            />
                        </div>

                        {/* Notes */}
                        <div className="space-y-2">
                            <Label htmlFor="notes">Notes</Label>
                            <Textarea
                                id="notes"
                                value={formData.notes || ''}
                                onChange={(e) => handleInputChange('notes', e.target.value)}
                                placeholder="Additional notes for the invoice"
                                rows={2}
                            />
                        </div>
                    </div>

                    <DialogFooter className="flex gap-2 sm:gap-0">
                        <Button variant="outline" onClick={handlePreview}>
                            <Eye className="h-4 w-4 mr-2" />
                            Preview
                        </Button>
                        <Button onClick={handleSave} disabled={isSaving || !formData.studentName}>
                            {isSaving ? (
                                <Loader2 className="h-4 w-4 animate-spin mr-2" />
                            ) : null}
                            Create Invoice
                        </Button>
                    </DialogFooter>
                </DialogContent>
            </Dialog>

            {/* Preview Dialog */}
            <InvoicePreview
                invoice={previewInvoice}
                open={showPreview}
                onOpenChange={setShowPreview}
            />
        </>
    );
}
