/**
 * Invoice Generator Service
 * Handles invoice creation, calculation, and PDF generation
 */

import type { Invoice, InvoiceStatus } from '@/types/database';
import { BRAND_NAME } from '@/lib/brand';

export interface InvoiceData {
    studentName: string;
    courseName: string;
    rtoName: string;
    tuitionFee: number;
    materialFee: number;
    applicationFee: number;
    otherFees?: number;
    discount?: number;
    dueDate?: string;
    notes?: string;
    applicationId?: string;
    partnerId?: string;
}

export interface InvoiceLineItem {
    description: string;
    amount: number;
}

export interface GeneratedInvoice {
    invoiceNumber: string;
    date: string;
    dueDate: string;
    studentName: string;
    courseName: string;
    rtoName: string;
    lineItems: InvoiceLineItem[];
    subtotal: number;
    discount: number;
    total: number;
    status: InvoiceStatus;
    notes?: string;
}

/**
 * Calculate invoice totals from fee components
 */
export function calculateInvoiceTotals(data: InvoiceData): {
    subtotal: number;
    discount: number;
    total: number;
    lineItems: InvoiceLineItem[];
} {
    const lineItems: InvoiceLineItem[] = [];

    if (data.tuitionFee > 0) {
        lineItems.push({ description: 'Tuition Fee', amount: data.tuitionFee });
    }
    if (data.materialFee > 0) {
        lineItems.push({ description: 'Material Fee', amount: data.materialFee });
    }
    if (data.applicationFee > 0) {
        lineItems.push({ description: 'Application Fee', amount: data.applicationFee });
    }
    if (data.otherFees && data.otherFees > 0) {
        lineItems.push({ description: 'Other Fees', amount: data.otherFees });
    }

    const subtotal = lineItems.reduce((sum, item) => sum + item.amount, 0);
    const discount = data.discount || 0;
    const total = Math.max(0, subtotal - discount);

    return { subtotal, discount, total, lineItems };
}

/**
 * Generate invoice data structure for PDF rendering
 */
export function generateInvoiceData(
    invoiceNumber: string,
    data: InvoiceData
): GeneratedInvoice {
    const { subtotal, discount, total, lineItems } = calculateInvoiceTotals(data);
    const today = new Date();
    const dueDate = data.dueDate
        ? new Date(data.dueDate)
        : new Date(today.getTime() + 30 * 24 * 60 * 60 * 1000); // 30 days from now

    return {
        invoiceNumber,
        date: today.toISOString().split('T')[0],
        dueDate: dueDate.toISOString().split('T')[0],
        studentName: data.studentName,
        courseName: data.courseName,
        rtoName: data.rtoName,
        lineItems,
        subtotal,
        discount,
        total,
        status: 'draft',
        notes: data.notes,
    };
}

/**
 * Format currency for display
 */
export function formatCurrency(amount: number, currency = 'AUD'): string {
    return new Intl.NumberFormat('en-AU', {
        style: 'currency',
        currency,
    }).format(amount);
}

/**
 * Generate invoice number (client-side preview, actual generated by DB)
 */
export function generatePreviewInvoiceNumber(): string {
    const year = new Date().getFullYear();
    const random = Math.floor(Math.random() * 9999)
        .toString()
        .padStart(4, '0');
    return `INV-${year}-${random}`;
}

/**
 * Generate HTML content for invoice (used for PDF generation)
 */
export function generateInvoiceHTML(invoice: GeneratedInvoice): string {
    const lineItemsHTML = invoice.lineItems
        .map(
            (item) => `
            <tr>
                <td style="padding: 12px; border-bottom: 1px solid #e5e7eb;">${item.description}</td>
                <td style="padding: 12px; border-bottom: 1px solid #e5e7eb; text-align: right;">${formatCurrency(item.amount)}</td>
            </tr>
        `
        )
        .join('');

    return `
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <style>
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            margin: 0;
            padding: 40px;
            color: #1f2937;
            line-height: 1.5;
        }
        .header {
            display: flex;
            justify-content: space-between;
            align-items: flex-start;
            margin-bottom: 40px;
            border-bottom: 2px solid #6366f1;
            padding-bottom: 20px;
        }
        .logo {
            font-size: 28px;
            font-weight: 700;
            color: #6366f1;
        }
        .logo span {
            color: #a855f7;
        }
        .invoice-details {
            text-align: right;
        }
        .invoice-number {
            font-size: 24px;
            font-weight: 600;
            color: #374151;
        }
        .section {
            margin-bottom: 30px;
        }
        .section-title {
            font-size: 12px;
            text-transform: uppercase;
            color: #6b7280;
            margin-bottom: 8px;
            letter-spacing: 0.5px;
        }
        .billing-info {
            display: flex;
            justify-content: space-between;
        }
        .billing-box {
            width: 45%;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        th {
            background: #f3f4f6;
            padding: 12px;
            text-align: left;
            font-weight: 600;
            font-size: 12px;
            text-transform: uppercase;
            color: #374151;
        }
        th:last-child {
            text-align: right;
        }
        .totals {
            margin-top: 20px;
            text-align: right;
        }
        .totals-row {
            display: flex;
            justify-content: flex-end;
            padding: 8px 0;
        }
        .totals-label {
            width: 150px;
            text-align: right;
            padding-right: 20px;
        }
        .totals-value {
            width: 120px;
            text-align: right;
            font-weight: 500;
        }
        .totals-row.total {
            border-top: 2px solid #e5e7eb;
            font-size: 18px;
            font-weight: 700;
            color: #6366f1;
        }
        .footer {
            margin-top: 60px;
            padding-top: 20px;
            border-top: 1px solid #e5e7eb;
            font-size: 12px;
            color: #6b7280;
        }
        .payment-info {
            background: #f9fafb;
            padding: 20px;
            border-radius: 8px;
            margin-top: 30px;
        }
        .payment-title {
            font-weight: 600;
            margin-bottom: 10px;
        }
        .notes {
            background: #fef3c7;
            padding: 15px;
            border-radius: 8px;
            margin-top: 20px;
            font-size: 14px;
        }
    </style>
</head>
<body>
    <div class="header">
        <div class="logo">${BRAND_NAME}</div>
        <div class="invoice-details">
            <div class="invoice-number">${invoice.invoiceNumber}</div>
            <div style="color: #6b7280; margin-top: 4px;">Invoice Date: ${invoice.date}</div>
            <div style="color: #6b7280;">Due Date: ${invoice.dueDate}</div>
        </div>
    </div>

    <div class="billing-info section">
        <div class="billing-box">
            <div class="section-title">Bill To</div>
            <div style="font-weight: 600; font-size: 16px;">${invoice.studentName}</div>
        </div>
        <div class="billing-box">
            <div class="section-title">Course Details</div>
            <div style="font-weight: 600;">${invoice.courseName}</div>
            <div style="color: #6b7280;">${invoice.rtoName}</div>
        </div>
    </div>

    <div class="section">
        <table>
            <thead>
                <tr>
                    <th>Description</th>
                    <th>Amount</th>
                </tr>
            </thead>
            <tbody>
                ${lineItemsHTML}
            </tbody>
        </table>

        <div class="totals">
            <div class="totals-row">
                <div class="totals-label">Subtotal</div>
                <div class="totals-value">${formatCurrency(invoice.subtotal)}</div>
            </div>
            ${invoice.discount > 0
            ? `
            <div class="totals-row">
                <div class="totals-label">Discount</div>
                <div class="totals-value">-${formatCurrency(invoice.discount)}</div>
            </div>
            `
            : ''
        }
            <div class="totals-row total">
                <div class="totals-label">Total Due</div>
                <div class="totals-value">${formatCurrency(invoice.total)}</div>
            </div>
        </div>
    </div>

    ${invoice.notes
            ? `
    <div class="notes">
        <strong>Notes:</strong> ${invoice.notes}
    </div>
    `
            : ''
        }

    <div class="payment-info">
        <div class="payment-title">Payment Information</div>
        <div>Bank: Commonwealth Bank of Australia</div>
        <div>Account Name: ${BRAND_NAME}</div>
        <div>BSB: 062-000</div>
        <div>Account Number: 1234 5678</div>
        <div style="margin-top: 10px; font-style: italic;">Reference: ${invoice.invoiceNumber}</div>
    </div>

    <div class="footer">
        <div>Thank you for choosing ${BRAND_NAME}.</div>
        <div style="margin-top: 5px;">For questions about this invoice, please contact accounts@lumiere.edu.au</div>
    </div>
</body>
</html>
    `;
}

/**
 * Convert database Invoice record to GeneratedInvoice format
 */
export function invoiceToGenerated(invoice: Invoice): GeneratedInvoice {
    const lineItems: InvoiceLineItem[] = [];

    if (invoice.tuition_fee > 0) {
        lineItems.push({ description: 'Tuition Fee', amount: invoice.tuition_fee });
    }
    if (invoice.material_fee > 0) {
        lineItems.push({ description: 'Material Fee', amount: invoice.material_fee });
    }
    if (invoice.application_fee > 0) {
        lineItems.push({ description: 'Application Fee', amount: invoice.application_fee });
    }
    if (invoice.other_fees > 0) {
        lineItems.push({ description: 'Other Fees', amount: invoice.other_fees });
    }

    const subtotal = lineItems.reduce((sum, item) => sum + item.amount, 0);

    return {
        invoiceNumber: invoice.invoice_number,
        date: invoice.created_at.split('T')[0],
        dueDate: invoice.due_date || '',
        studentName: invoice.student_name,
        courseName: invoice.course_name || '',
        rtoName: invoice.rto_name || '',
        lineItems,
        subtotal,
        discount: invoice.discount,
        total: invoice.total_amount,
        status: invoice.status,
        notes: invoice.notes || undefined,
    };
}

// ===========================================
// Bulk Invoice Operations
// ===========================================

import { createClient } from '@/lib/supabase/client';
import { ACTIVE_RECORD_FILTER } from '@/lib/soft-delete';
import type { BulkOperation } from '@/types/database';

export interface BulkInvoiceOptions {
    dueInDays?: number;
    notes?: string;
    invoiceType?: 'customer' | 'agent';
    autoSyncXero?: boolean;
}

async function isXeroConnected(): Promise<boolean> {
    try {
        const response = await fetch('/api/xero/status');
        if (!response.ok) return false;
        const data = await response.json();
        return Boolean(data?.connected);
    } catch {
        return false;
    }
}

async function trySyncInvoiceToXero(invoiceId: string): Promise<void> {
    try {
        await fetch('/api/xero/sync', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ action: 'sync_invoice', invoiceId }),
        });
    } catch (error) {
        console.warn('Auto-sync invoice to Xero failed:', error);
    }
}

/**
 * Create a single invoice in the database
 */
export async function createInvoice(
    data: InvoiceData,
    options: BulkInvoiceOptions = {}
): Promise<Invoice | null> {
    const supabase = createClient();
    const { subtotal, discount, total } = calculateInvoiceTotals(data);

    const { data: invoice, error } = await supabase
        .from('invoices')
        .insert({
            application_id: data.applicationId || null,
            partner_id: data.partnerId || null,
            student_name: data.studentName,
            course_name: data.courseName,
            rto_name: data.rtoName,
            tuition_fee: data.tuitionFee || 0,
            material_fee: data.materialFee || 0,
            application_fee: data.applicationFee || 0,
            other_fees: data.otherFees || 0,
            discount: discount,
            subtotal: subtotal,
            total_amount: total,
            due_date: data.dueDate || null,
            notes: data.notes || null,
        })
        .select()
        .single();

    if (error) {
        console.error('Error creating invoice:', error);
        return null;
    }

    if (options.autoSyncXero) {
        const connected = await isXeroConnected();
        if (connected && invoice?.id) {
            await trySyncInvoiceToXero(invoice.id);
        }
    }

    return invoice;
}

/**
 * Create bulk invoices for multiple applications
 */
export async function createBulkInvoices(
    applicationIds: string[],
    options: BulkInvoiceOptions = {}
): Promise<{ success: boolean; operation?: BulkOperation; error?: string }> {
    const supabase = createClient();

    // Get current user
    const { data: { user } } = await supabase.auth.getUser();
    if (!user) {
        return { success: false, error: 'Not authenticated' };
    }

    // Create bulk operation record
    const { data: operation, error: opError } = await supabase
        .from('bulk_operations')
        .insert({
            type: 'invoice',
            status: 'processing',
            total_items: applicationIds.length,
            created_by: user.id,
        })
        .select()
        .single();

    if (opError) {
        return { success: false, error: 'Failed to create bulk operation' };
    }

    // Fetch applications with their offerings
    const { data: applications, error: appError } = await supabase
        .from('applications')
        .select(`
            id,
            student_first_name,
            student_last_name,
            quoted_tuition,
            quoted_materials,
            partner_id,
            offering:rto_offerings(
                tuition_fee_onshore,
                material_fee,
                application_fee,
                qualification:qualifications(name),
                rto:rtos(name)
            )
        `)
        .or(ACTIVE_RECORD_FILTER)
        .in('id', applicationIds);

    if (appError || !applications) {
        await supabase
            .from('bulk_operations')
            .update({ status: 'failed' })
            .eq('id', operation.id);
        return { success: false, error: 'Failed to fetch applications' };
    }

    let processed = 0;
    let failed = 0;
    const errorLog: Array<{ item_id: string; error: string }> = [];
    const createdInvoiceIds: string[] = [];
    const dueDate = new Date();
    dueDate.setDate(dueDate.getDate() + (options.dueInDays || 30));

    // Create invoices for each application
    for (const app of applications) {
        try {
            // Supabase returns nested relations as objects (not arrays) for single foreign key
            const offering = app.offering as unknown as {
                tuition_fee_onshore: number;
                material_fee: number;
                application_fee: number;
                qualification: { name: string } | null;
                rto: { name: string } | null;
            } | null;

            const tuitionFee = app.quoted_tuition || offering?.tuition_fee_onshore || 0;
            const materialFee = app.quoted_materials || offering?.material_fee || 0;
            const applicationFee = offering?.application_fee || 0;
            const total = tuitionFee + materialFee + applicationFee;

            const { data: createdInvoice, error } = await supabase
                .from('invoices')
                .insert({
                    application_id: app.id,
                    partner_id: app.partner_id || null,
                    student_name: `${app.student_first_name} ${app.student_last_name}`,
                    course_name: offering?.qualification?.name || 'Course',
                    rto_name: offering?.rto?.name || 'RTO',
                    tuition_fee: tuitionFee,
                    material_fee: materialFee,
                    application_fee: applicationFee,
                    other_fees: 0,
                    discount: 0,
                    subtotal: total,
                    total_amount: total,
                    due_date: dueDate.toISOString().split('T')[0],
                    notes: options.notes || null,
                    invoice_type: options.invoiceType || 'customer',
                })
                .select('id')
                .single();

            if (error) {
                failed++;
                errorLog.push({ item_id: app.id, error: error.message });
            } else {
                processed++;
                if (createdInvoice?.id) createdInvoiceIds.push(createdInvoice.id);
            }
        } catch {
            failed++;
            errorLog.push({ item_id: app.id, error: 'Unknown error' });
        }
    }

    if (options.autoSyncXero) {
        const connected = await isXeroConnected();
        if (connected) {
            for (const invoiceId of createdInvoiceIds) {
                await trySyncInvoiceToXero(invoiceId);
            }
        }
    }

    // Update operation status
    await supabase
        .from('bulk_operations')
        .update({
            status: failed === applicationIds.length ? 'failed' : 'completed',
            processed_items: processed,
            failed_items: failed,
            error_log: errorLog,
            completed_at: new Date().toISOString(),
        })
        .eq('id', operation.id);

    return {
        success: true,
        operation: {
            ...operation,
            processed_items: processed,
            failed_items: failed,
            status: failed === applicationIds.length ? 'failed' : 'completed',
        } as BulkOperation,
    };
}

/**
 * Get all invoices with filters
 */
export async function getInvoices(filters?: {
    status?: InvoiceStatus;
    partnerId?: string;
    fromDate?: string;
    toDate?: string;
}): Promise<Invoice[]> {
    const supabase = createClient();

    const buildQuery = (options: { includeDeletedFilter: boolean; includeRelations: boolean }) => {
        let query = supabase
            .from('invoices')
            .select(options.includeRelations
                ? '*,partner:partners(id,company_name),application:applications(id,application_number,student_uid)'
                : '*');

        if (options.includeDeletedFilter) {
            query = query.or('is_deleted.is.null,is_deleted.eq.false');
        }

        if (filters?.status) {
            query = query.eq('status', filters.status);
        }
        if (filters?.partnerId) {
            query = query.eq('partner_id', filters.partnerId);
        }
        if (filters?.fromDate) {
            query = query.gte('created_at', filters.fromDate);
        }
        if (filters?.toDate) {
            query = query.lte('created_at', filters.toDate);
        }

        return query.order('created_at', { ascending: false });
    };

    const isMissingIsDeletedColumn = (message: string) => (
        message.includes('is_deleted') && (message.includes('column') || message.includes('schema cache'))
    );

    const isRelationOrPermissionError = (message: string) => (
        message.includes('relationship')
        || message.includes('foreign key')
        || message.includes('could not find')
        || message.includes('permission denied')
    );

    let { data, error } = await buildQuery({ includeDeletedFilter: true, includeRelations: true });

    const message = (error?.message || '').toLowerCase();

    if (error && isMissingIsDeletedColumn(message)) {
        const fallback = await buildQuery({ includeDeletedFilter: false, includeRelations: true });
        data = fallback.data;
        error = fallback.error;
    }

    const messageAfterDeletedFallback = (error?.message || '').toLowerCase();
    if (error && isRelationOrPermissionError(messageAfterDeletedFallback)) {
        let fallback = await buildQuery({ includeDeletedFilter: true, includeRelations: false });

        const fallbackMessage = (fallback.error?.message || '').toLowerCase();
        if (fallback.error && isMissingIsDeletedColumn(fallbackMessage)) {
            fallback = await buildQuery({ includeDeletedFilter: false, includeRelations: false });
        }

        data = fallback.data;
        error = fallback.error;
    }

    if (error) {
        console.error('Error fetching invoices:', error);
        return [];
    }

    const invoices = (data || []) as unknown as Array<Invoice & { is_deleted?: boolean | null }>;

    return invoices
        .filter((invoice) => {
            return invoice.is_deleted !== true;
        });
}

/**
 * Update invoice status
 */
export async function updateInvoiceStatus(
    id: string,
    status: InvoiceStatus,
    paymentInfo?: { reference?: string; method?: string }
): Promise<boolean> {
    const supabase = createClient();

    const updateData: Record<string, unknown> = { status };

    if (status === 'paid') {
        updateData.paid_at = new Date().toISOString();
        if (paymentInfo?.reference) updateData.payment_reference = paymentInfo.reference;
        if (paymentInfo?.method) updateData.payment_method = paymentInfo.method;
    }

    const { error } = await supabase
        .from('invoices')
        .update(updateData)
        .eq('id', id);

    return !error;
}

/**
 * Get invoice by ID
 */
export async function getInvoiceById(id: string): Promise<Invoice | null> {
    const supabase = createClient();

    const { data, error } = await supabase
        .from('invoices')
        .select('*, partner:partners(*), application:applications(*)')
        .eq('id', id)
        .single();

    if (error) {
        console.error('Error fetching invoice:', error);
        return null;
    }

    return data;
}

/**
 * Delete invoice (soft delete)
 */
export async function deleteInvoice(id: string): Promise<boolean> {
    const supabase = createClient();
    const { data: { user } } = await supabase.auth.getUser();

    const { error } = await supabase
        .from('invoices')
        .update({
            is_deleted: true,
            deleted_at: new Date().toISOString(),
            deleted_by: user?.id || null,
        })
        .eq('id', id);

    return !error;
}

// ===========================================
// Invoice Sending Functions
// ===========================================

export interface InvoiceSendResult {
    success: boolean;
    invoiceId: string;
    recipient: string;
    error?: string;
}

/**
 * Send single invoice email
 */
export async function sendInvoiceEmail(
    invoiceId: string,
    recipientType: 'student' | 'agent'
): Promise<InvoiceSendResult> {
    const supabase = createClient();
    const { data: { user } } = await supabase.auth.getUser();

    // Fetch invoice with relations
    const { data: invoice, error: fetchError } = await supabase
        .from('invoices')
        .select(`
            *,
            application:applications(
                student_email,
                student_first_name,
                student_last_name,
                partner:partners(contact_email, company_name)
            )
        `)
        .eq('id', invoiceId)
        .single();

    if (fetchError || !invoice) {
        return { success: false, invoiceId, recipient: '', error: 'Invoice not found' };
    }

    const app = invoice.application as {
        student_email: string | null;
        student_first_name: string;
        student_last_name: string;
        partner: { contact_email: string | null; company_name: string } | null;
    } | null;

    // Determine recipient
    let recipientEmail: string | null = null;
    let recipientName: string = '';

    if (recipientType === 'student') {
        recipientEmail = app?.student_email || null;
        recipientName = `${app?.student_first_name || ''} ${app?.student_last_name || ''}`.trim();
    } else {
        recipientEmail = app?.partner?.contact_email || null;
        recipientName = app?.partner?.company_name || 'Agent';
    }

    if (!recipientEmail) {
        return {
            success: false,
            invoiceId,
            recipient: '',
            error: `No ${recipientType} email available`
        };
    }

    // Queue the email
    const { error: queueError } = await supabase
        .from('notification_queue')
        .insert({
            channel: 'email',
            recipient: recipientEmail,
            subject: `Invoice ${invoice.invoice_number} - ${invoice.student_name}`,
            body: `
Dear ${recipientName},

Please find attached invoice ${invoice.invoice_number} for ${invoice.student_name}.

Amount Due: ${formatCurrency(invoice.total_amount)}
Due Date: ${invoice.due_date || 'Upon receipt'}

If you have any questions regarding this invoice, please contact us.

Best regards,
${BRAND_NAME}
            `.trim(),
            invoice_id: invoiceId,
            application_id: invoice.application_id,
            status: 'pending',
            scheduled_at: new Date().toISOString(),
            created_by: user?.id || null,
            metadata: {
                invoice_number: invoice.invoice_number,
                recipient_type: recipientType,
                amount: invoice.total_amount,
            },
        });

    if (queueError) {
        return { success: false, invoiceId, recipient: recipientEmail, error: queueError.message };
    }

    // Update invoice sent tracking
    await supabase
        .from('invoices')
        .update({
            sent_at: new Date().toISOString(),
            sent_to: recipientEmail,
            sent_via: 'email',
            send_count: (invoice.send_count || 0) + 1,
            status: invoice.status === 'draft' ? 'sent' : invoice.status,
        })
        .eq('id', invoiceId);

    // Log to notification_logs
    await supabase
        .from('notification_logs')
        .insert({
            channel: 'email',
            recipient: recipientEmail,
            recipient_name: recipientName,
            subject: `Invoice ${invoice.invoice_number}`,
            status: 'sent',
            sent_by: user?.id || null,
            invoice_id: invoiceId,
            message_type: 'invoice',
        });

    return { success: true, invoiceId, recipient: recipientEmail };
}

/**
 * Send bulk invoice emails - groups by agent for efficiency
 */
export async function sendBulkInvoiceEmails(
    invoiceIds: string[],
    sendTo: 'student' | 'agent' = 'agent'
): Promise<{
    success: boolean;
    sent: number;
    failed: number;
    results: InvoiceSendResult[];
}> {
    const supabase = createClient();
    const { data: { user } } = await supabase.auth.getUser();

    // Fetch all invoices with relations
    const { data: invoices, error } = await supabase
        .from('invoices')
        .select(`
            *,
            partner:partners(id, contact_email, company_name),
            application:applications(
                id,
                student_email,
                student_first_name,
                student_last_name
            )
        `)
        .in('id', invoiceIds);

    if (error || !invoices) {
        return { success: false, sent: 0, failed: invoiceIds.length, results: [] };
    }

    const results: InvoiceSendResult[] = [];

    if (sendTo === 'agent') {
        // Group invoices by agent for batch sending
        const invoicesByAgent = new Map<string, typeof invoices>();

        for (const inv of invoices) {
            const partner = inv.partner as { id: string; contact_email: string | null; company_name: string } | null;
            const agentId = partner?.id || 'no-agent';

            if (!invoicesByAgent.has(agentId)) {
                invoicesByAgent.set(agentId, []);
            }
            invoicesByAgent.get(agentId)!.push(inv);
        }

        // Send one email per agent with all their students' invoices
        for (const [agentId, agentInvoices] of invoicesByAgent) {
            const partner = agentInvoices[0].partner as {
                contact_email: string | null;
                company_name: string
            } | null;

            if (!partner?.contact_email) {
                for (const inv of agentInvoices) {
                    results.push({
                        success: false,
                        invoiceId: inv.id,
                        recipient: '',
                        error: 'No agent email',
                    });
                }
                continue;
            }

            // Create summary email for agent
            const invoiceList = agentInvoices.map(inv =>
                `• ${inv.invoice_number}: ${inv.student_name} - ${formatCurrency(inv.total_amount)}`
            ).join('\n');

            const totalAmount = agentInvoices.reduce((sum, inv) => sum + (inv.total_amount || 0), 0);

            const { error: queueError } = await supabase
                .from('notification_queue')
                .insert({
                    channel: 'email',
                    recipient: partner.contact_email,
                    subject: `${agentInvoices.length} Invoice(s) for Your Students`,
                    body: `
Dear ${partner.company_name},

Please find below the invoices for your students:

${invoiceList}

Total Amount: ${formatCurrency(totalAmount)}

If you have any questions regarding these invoices, please contact us.

Best regards,
${BRAND_NAME}
                    `.trim(),
                    status: 'pending',
                    scheduled_at: new Date().toISOString(),
                    created_by: user?.id || null,
                    metadata: {
                        invoice_ids: agentInvoices.map(i => i.id),
                        agent_id: agentId,
                        total_amount: totalAmount,
                    },
                });

            if (queueError) {
                for (const inv of agentInvoices) {
                    results.push({
                        success: false,
                        invoiceId: inv.id,
                        recipient: partner.contact_email,
                        error: queueError.message,
                    });
                }
            } else {
                // Update all invoices for this agent
                for (const inv of agentInvoices) {
                    await supabase
                        .from('invoices')
                        .update({
                            sent_at: new Date().toISOString(),
                            sent_to: partner.contact_email,
                            sent_via: 'email',
                            send_count: (inv.send_count || 0) + 1,
                            status: inv.status === 'draft' ? 'sent' : inv.status,
                        })
                        .eq('id', inv.id);

                    results.push({
                        success: true,
                        invoiceId: inv.id,
                        recipient: partner.contact_email,
                    });
                }

                // Log the batch send
                await supabase
                    .from('notification_logs')
                    .insert({
                        channel: 'email',
                        recipient: partner.contact_email,
                        recipient_name: partner.company_name,
                        subject: `${agentInvoices.length} Invoice(s)`,
                        status: 'sent',
                        sent_by: user?.id || null,
                        message_type: 'invoice',
                    });
            }
        }
    } else {
        // Send individual emails to students
        for (const inv of invoices) {
            const result = await sendInvoiceEmail(inv.id, 'student');
            results.push(result);
        }
    }

    const sent = results.filter(r => r.success).length;
    const failed = results.filter(r => !r.success).length;

    return { success: failed === 0, sent, failed, results };
}

/**
 * Check which applications already have invoices
 */
export async function getInvoicesByApplicationIds(
    applicationIds: string[]
): Promise<Map<string, Invoice>> {
    const supabase = createClient();

    const { data, error } = await supabase
        .from('invoices')
        .select('*')
        .in('application_id', applicationIds)
        .eq('is_deleted', false);

    if (error) {
        console.error('Error fetching invoices by application:', error);
        return new Map();
    }

    const map = new Map<string, Invoice>();
    for (const inv of data || []) {
        if (inv.application_id) {
            map.set(inv.application_id, inv);
        }
    }

    return map;
}
